MySiteProject/Models/Entities/AboutMe.cs
using System.ComponentModel.DataAnnotations;

namespace MySiteProject.Models.Entities
{
    public class AboutMe
    {
        [Key]
        public int AboutMeID { get; set; }
        [MaxLength(100)]
        public string Title { get; set; }
        public string Description { get; set; }
        public DateTime DescriptionDate { get; set; }
        [MaxLength(255)]
        public string? DescriptionPhoto { get; set; }
    }
}

MySiteProject/Models/Entities/Contact.cs
using System.ComponentModel.DataAnnotations;

namespace MySiteProject.Models.Entities
{
    public class Contact
    {
        [Key]
        public int ContactID { get; set; }
        [MaxLength(50)]
        public string Name { get; set; }
        [MaxLength(50)]
        public string Surname { get; set; }
        [MaxLength(255)]
        public string Email { get; set; }
        public string Message { get; set; }
    }
}

MySiteProject/Controllers/AboutMeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MySiteProject.Models.Context;
using MySiteProject.Models.Entities;

namespace MySiteProject.Controllers
{
    public class AboutMeController : Controller
    {
        private readonly MySiteContext _context;

        public AboutMeController(MySiteContext context)
        {
            _context = context;
        }

        // GET: AboutMe
        public async Task<IActionResult> Index()
        {
              return View(await _context.AboutMes.ToListAsync());
        }

        // GET: AboutMe/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.AboutMes == null)
            {
                return NotFound();
            }

            var aboutMe = await _context.AboutMes
                .FirstOrDefaultAsync(m => m.AboutMeID == id);
            if (aboutMe == null)
            {
                return NotFound();
            }

            return View(aboutMe);
        }

        // GET: AboutMe/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AboutMe/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AboutMeID,Title,Description,DescriptionDate,DescriptionPhoto")] AboutMe aboutMe,IFormFile DescriptionPhoto)
        {
            if (ModelState.IsValid)
            {
                //--File adding settings--
                if (DescriptionPhoto != null)
                {
                    string imageName = DescriptionPhoto.FileName;
                    string path = Path.Combine(Directory.GetCurrentDirectory(), $"wwwroot/assets/img/aboutme/{imageName}");
                    var stream = new FileStream(path, FileMode.OpenOrCreate);
                    aboutMe.DescriptionPhoto = imageName;
                    DescriptionPhoto.CopyTo(stream);
                }
                _context.Add(aboutMe);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(aboutMe);
        }

        // GET: AboutMe/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.AboutMes == null)
            {
                return NotFound();
            }

            var aboutMe = await _context.AboutMes.FindAsync(id);
            if (aboutMe == null)
            {
                return NotFound();
            }
            return View(aboutMe);
        }

        // POST: AboutMe/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AboutMeID,Title,Description,DescriptionDate,DescriptionPhoto")] AboutMe aboutMe, IFormFile DescriptionPhoto)
        {
            if (id != aboutMe.AboutMeID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (DescriptionPhoto != null)
                    {
                        string imageName = DescriptionPhoto.FileName;
                        string path = Path.Combine(Directory.GetCurrentDirectory(), $"wwwroot/assets/img/aboutme/{imageName}");
                        var stream = new FileStream(path, FileMode.OpenOrCreate);
                        aboutMe.DescriptionPhoto = imageName;
                        DescriptionPhoto.CopyTo(stream);
                    }
                    _context.Update(aboutMe);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AboutMeExists(aboutMe.AboutMeID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(aboutMe);
        }

        // GET: AboutMe/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.AboutMes == null)
            {
                return NotFound();
            }

            var aboutMe = await _context.AboutMes
                .FirstOrDefaultAsync(m => m.AboutMeID == id);
            if (aboutMe == null)
            {
                return NotFound();
            }

            return View(aboutMe);
        }

        // POST: AboutMe/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.AboutMes == null)
            {
                return Problem("Entity set 'MySiteContext.AboutMes'  is null.");
            }
            var aboutMe = await _context.AboutMes.FindAsync(id);
            if (aboutMe != null)
            {
                _context.AboutMes.Remove(aboutMe);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AboutMeExists(int id)
        {
          return _context.AboutMes.Any(e => e.AboutMeID == id);
        }
    }
}

MySiteProject/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MySiteProject.Models.Context;
using MySiteProject.Models.Entities;

namespace MySiteProject.Controllers
{
    public class ContactController : Controller
    {
        private readonly MySiteContext _context;

        public ContactController(MySiteContext context)
        {
            _context = context;
        }

        // GET: Contact
        public async Task<IActionResult> Index()
        {
              return View(await _context.Contacts.ToListAsync());
        }

        
        // GET: Contact/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Contacts == null)
            {
                return NotFound();
            }

            var contact = await _context.Contacts
                .FirstOrDefaultAsync(m => m.ContactID == id);
            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }

        // POST: Contact/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Contacts == null)
            {
                return Problem("Entity set 'MySiteContext.Contacts'  is null.");
            }
            var contact = await _context.Contacts.FindAsync(id);
            if (contact != null)
            {
                _context.Contacts.Remove(contact);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContactExists(int id)
        {
          return _context.Contacts.Any(e => e.ContactID == id);
        }
    }
}

MySiteProject/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MySiteProject.Models.Context;
using MySiteProject.Models.Entities;

namespace MySiteProject.Controllers
{
    public class ProjectController : Controller
    {
        private readonly MySiteContext _context;

        public ProjectController(MySiteContext context)
        {
            _context = context;
        }

        // GET: Project
        public async Task<IActionResult> Index()
        {
              return View(await _context.ProjectInfos.ToListAsync());
        }

        // GET: Project/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ProjectInfos == null)
            {
                return NotFound();
            }

            var projectInfo = await _context.ProjectInfos
                .FirstOrDefaultAsync(m => m.ProjectID == id);
            if (projectInfo == null)
            {
                return NotFound();
            }

            return View(projectInfo);
        }

        // GET: Project/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Project/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProjectInfo projectInfo,IFormFile projectPhoto)
        {
            if (ModelState.IsValid)
            {
                if (projectPhoto != null)
                {
                    string imageName = projectPhoto.FileName;
                    string path = Path.Combine(Directory.GetCurrentDirectory(), $"wwwroot/assets/img/project/{imageName}");
                    var stream = new FileStream(path,FileMode.OpenOrCreate);
                    projectInfo.ProjectPhoto = imageName;
                    projectPhoto.CopyTo(stream);
                }
                _context.Add(projectInfo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(projectInfo);
        }

        // GET: Project/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ProjectInfos == null)
            {
                return NotFound();
            }

            var projectInfo = await _context.ProjectInfos.FindAsync(id);
            if (projectInfo == null)
            {
                return NotFound();
            }
            return View(projectInfo);
        }

        // POST: Project/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProjectID,ProjectName,ProjectDescription,ProjectDate,ProjectPhoto")] ProjectInfo projectInfo, IFormFile projectPhoto)
        {
            if (id != projectInfo.ProjectID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (projectPhoto != null)
                    {
                        string imageName = projectPhoto.FileName;
                        string path = Path.Combine(Directory.GetCurrentDirectory(), $"wwwroot/assets/img/project/{imageName}");
                        var stream = new FileStream(path, FileMode.OpenOrCreate);
                        projectInfo.ProjectPhoto = imageName;
                        projectPhoto.CopyTo(stream);
                    }
                    _context.Update(projectInfo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectInfoExists(projectInfo.ProjectID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(projectInfo);
        }

        // GET: Project/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ProjectInfos == null)
            {
                return NotFound();
            }

            var projectInfo = await _context.ProjectInfos
                .FirstOrDefaultAsync(m => m.ProjectID == id);
            if (projectInfo == null)
            {
                return NotFound();
            }

            return View(projectInfo);
        }

        // POST: Project/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ProjectInfos == null)
            {
                return Problem("Entity set 'MySiteContext.ProjectInfos'  is null.");
            }
            var projectInfo = await _context.ProjectInfos.FindAsync(id);
            if (projectInfo != null)
            {
                _context.ProjectInfos.Remove(projectInfo);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProjectInfoExists(int id)
        {
          return _context.ProjectInfos.Any(e => e.ProjectID == id);
        }
    }
}

MySiteProject/Views/Shared/_AboutMe.cshtml
@{
    var aboutMedata = ViewBag.aboutMe;
    int counter = 0;
    string timelineInverted;
}
<section class="page-section" id="about">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">About Me</h2>
        </div>
        <ul class="timeline">
            @foreach (var item in aboutMedata)
            {
                string descrpitonDate = (item.DescriptionDate.Month.ToString() + "/" + item.DescriptionDate.Year.ToString());
                counter++;
                if (counter % 2 == 0)
                {
                    timelineInverted = "timeline-inverted";
                }
                else
                {
                    timelineInverted = "";
                }
                <li class="@timelineInverted">
                    <div class="timeline-image"><img class="rounded-circle img-fluid" src="/assets/img/aboutme/@item.DescriptionPhoto" alt="@item.DescriptionPhoto" /></div>
                    <div class="timeline-panel">
                        <div class="timeline-heading">
                            <h4 class="subheading">@item.Title</h4>
                            <h6>@(descrpitonDate)</h6>
                        </div>
                        <div class="timeline-body">                            
                            <a class="portfolio-link" data-bs-toggle="modal" href="#Model@(item.AboutMeID)">Details</a>
                        </div>
                    </div>
                </li>
                <!-- Portfolio modal popup-->
                <div class="portfolio-modal modal fade" id="Model@(item.AboutMeID)" tabindex="-1" role="dialog" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="close-modal" data-bs-dismiss="modal"><img src="/assets/img/close-icon.svg" alt="Close modal" /></div>
                            <div class="container">
                                <div class="row justify-content-center">
                                    <div class="col-lg-8">
                                        <div class="modal-body">
                                            <!-- Project details-->
                                            <h2 class="text-uppercase">@item.Title</h2>
                                            <p class="item-intro text-muted">@(descrpitonDate)</p>
                                            <img class="img-fluid d-block mx-auto" src="~/assets/img/project/@item.DescriptionPhoto" alt="@item.DescriptionPhoto" />
                                            <p>@Html.Raw(item.Description)</p>
                                            <ul class="list-inline">
                                                <li>
                                                    <strong>Title:</strong>
                                                    @item.Title
                                                </li>
                                                <li>
                                                    <strong>Date:</strong>
                                                    @(descrpitonDate)
                                                </li>
                                            </ul>
                                            <button class="btn btn-primary btn-xl text-uppercase" data-bs-dismiss="modal" type="button">
                                                <i class="fas fa-xmark me-1"></i>
                                                Close Project
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </ul>
    </div>


</section>

MySiteProject/Views/Shared/_Contact.cshtml
<section class="page-section" id="contact">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Contact Us</h2>
            <h3 class="section-subheading text-muted">@TempData["Message"]</h3>
        </div>
        <!-- * * * * * * * * * * * * * * *-->
        <!-- * * SB Forms Contact Form * *-->
        <!-- * * * * * * * * * * * * * * *-->
        <!-- This form is pre-integrated with SB Forms.-->
        <!-- To make this form functional, sign up at-->
        <!-- https://startbootstrap.com/solution/contact-forms-->
        <!-- to get an API token!-->
        <form action="/site/Contact" method="post" id="contactForm">
            <div class="row align-items-stretch mb-5">
                <div class="col-md-6">
                    <div class="form-group">
                        <!-- Name input-->
                        <input class="form-control" id="name" type="text" placeholder="Your Name *" data-sb-validations="required" name="Name" required/>
                        <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                    </div>
                    <div class="form-group">
                        <!-- Surname input-->
                        <input class="form-control" id="name" type="text" placeholder="Your Surname *" data-sb-validations="required" name="Surname" required/>
                        <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                    </div>
                    <div class="form-group">
                        <!-- Email address input-->
                        <input class="form-control" id="email" type="email" placeholder="Your Email *" data-sb-validations="required,email" name="Email" required/>
                        <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                        <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group form-group-textarea mb-md-0">
                        <!-- Message input-->
                        <textarea class="form-control" id="message" placeholder="Your Message *" data-sb-validations="required" name="Message" required></textarea>
                        <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
                    </div>
                </div>
            </div>
            <!-- Submit success message-->
            <!---->
            <!-- This is what your users will see when the form-->
            <!-- has successfully submitted-->
            <div class="d-none" id="submitSuccessMessage">
                <div class="text-center text-white mb-3">
                    <div class="fw-bolder">Form submission successful!</div>
                    To activate this form, sign up at
                    <br />
                    <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                </div>
            </div>
            <!-- Submit error message-->
            <!---->
            <!-- This is what your users will see when there is-->
            <!-- an error submitting the form-->
            <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
            <!-- Submit Button-->
            <div class="text-center"><button class="btn btn-primary" id="submitButton" type="submit">Send Message</button></div>
        </form>
    </div>
</section>

MySiteProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MySiteProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MySiteProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">My Site Project</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AboutMe" asp-action="Index">About Me</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Index">Project</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Security" asp-action="LogOut">LogOut</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MySiteProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MySiteProject/Views/Shared/_LayoutMySite.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title - My Site Project</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="/assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="/css/styles.css" rel="stylesheet" />
</head>
<body id="page-top">
    <!-- Navigation-->
    <partial name="_NavBar" />
    <!-- Masthead-->
    <partial name="_SiteHeader" />
    <!---->
    @RenderBody()
    <!-- About Me-->
    <partial name="_AboutMe" />
    <!-- Portfolio Grid-->    
    <partial name="_Projects" />
    <!-- Contact-->
    <partial name="_Contact" />
    <!-- Footer-->
    <partial name="_SiteFooter" />
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="/js/scripts.js"></script>
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>
</html>

MySiteProject/Views/Shared/_NavBar.cshtml
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="#page-top"><img src="/assets/img/navbar-logo.svg" alt="..." /></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars ms-1"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link" href="#about">About Me</a></li>
                    <li class="nav-item"><a class="nav-link" href="#portfolio">Portfolio</a></li>                    
                    <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

MySiteProject/Views/Shared/_Projects.cshtml
@model List<ProjectInfo>
<section class="page-section bg-light" id="portfolio">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Portfolio</h2>
        </div>
        <div class="row">
            @{
                int modelCounter = 0;                
            }
            @foreach (var item in Model)
            {
                string projectDate = (item.ProjectDate.Month.ToString() + "/" + item.ProjectDate.Year.ToString());
                modelCounter++;
                <div class="col-lg-4 col-sm-6 mb-4">
                    <!-- Portfolio item -->
                    <div class="portfolio-item">
                        <a class="portfolio-link" data-bs-toggle="modal" href="#Model@(modelCounter)">
                            <div class="portfolio-hover">
                                <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>
                            </div>
                            <img class="img-fluid" src="~/assets/img/project/@item.ProjectPhoto" alt="@item.ProjectPhoto" />
                        </a>
                        <div class="portfolio-caption">
                            <div class="portfolio-caption-heading">@item.ProjectName</div>
                        </div>
                    </div>
                </div>
                <!-- Portfolio modal popup-->
                <div class="portfolio-modal modal fade" id="Model@(modelCounter)" tabindex="-1" role="dialog" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="close-modal" data-bs-dismiss="modal"><img src="/assets/img/close-icon.svg" alt="Close modal" /></div>
                            <div class="container">
                                <div class="row justify-content-center">
                                    <div class="col-lg-8">
                                        <div class="modal-body">
                                            <!-- Project details-->
                                            <h2 class="text-uppercase">@item.ProjectName</h2>                                            
                                            <p class="item-intro text-muted">@(projectDate)</p>
                                            <img class="img-fluid d-block mx-auto" src="~/assets/img/project/@item.ProjectPhoto" alt="@item.ProjectPhoto" />
                                            <p>@Html.Raw(item.ProjectDescription)</p>
                                            <ul class="list-inline">
                                                <li>
                                                    <strong>Project Name:</strong>
                                                    @item.ProjectName
                                                </li>
                                                <li>
                                                    <strong>Project Date:</strong>
                                                    @(projectDate)
                                                </li>
                                            </ul>
                                            <button class="btn btn-primary btn-xl text-uppercase" data-bs-dismiss="modal" type="button">
                                                <i class="fas fa-xmark me-1"></i>
                                                Close Project
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }

        </div>


    </div>
</section>